# Clear scoreboards
scoreboard objectives remove CPU_registers
scoreboard objectives remove CPU_values
scoreboard objectives remove CPU_instructions
scoreboard objectives remove CPU_initialise
scoreboard objectives remove CPU_functions
# Remove pointer
kill @e[type=armor_stand,name=pointer]
kill @e[type=armor_stand,name=col1]
kill @e[type=armor_stand,name=col2]
kill @e[type=armor_stand,name=col3]
kill @e[type=armor_stand,name=col4]
kill @e[type=armor_stand,name=col5]
kill @e[type=armor_stand,name=col6]
kill @e[type=armor_stand,name=col7]
kill @e[type=armor_stand,name=col8]
kill @e[type=armor_stand,name=col9]
kill @e[type=armor_stand,name=col10]
kill @e[type=armor_stand,name=col11]
kill @e[type=armor_stand,name=col12]
kill @e[type=armor_stand,name=col13]
kill @e[type=armor_stand,name=col14]
kill @e[type=armor_stand,name=col15]
kill @e[type=armor_stand,name=col16]
kill @e[type=armor_stand,name=col17]
kill @e[type=armor_stand,name=col18]
kill @e[type=armor_stand,name=col19]
kill @e[type=armor_stand,name=col20]
kill @e[type=armor_stand,name=col21]
kill @e[type=armor_stand,name=col22]
kill @e[type=armor_stand,name=col23]
kill @e[type=armor_stand,name=col24]
kill @e[type=armor_stand,name=col25]
kill @e[type=armor_stand,name=col26]
kill @e[type=armor_stand,name=col27]
kill @e[type=armor_stand,name=col28]
kill @e[type=armor_stand,name=col29]
kill @e[type=armor_stand,name=col30]
kill @e[type=armor_stand,name=col31]
kill @e[type=armor_stand,name=col32]
kill @e[type=armor_stand,name=jmp]