# Reset position
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=0,score_CPU_values=0] ~ ~ ~ execute @e[type=armor_stand,name=col14,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] 486 54 -74
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col15,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] 486 54 -74
execute @e[type=armor_stand,name=pointer,score_CPU_values=-1] ~ ~ ~ execute @e[type=armor_stand,name=col16,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] 486 54 -74
# Jump if equal
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=0,score_CPU_values=0] ~ ~ ~ execute @e[type=armor_stand,name=col2,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col14,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~64 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=0,score_CPU_values=0] ~ ~ ~ execute @e[type=armor_stand,name=col3,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col14,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~32 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=0,score_CPU_values=0] ~ ~ ~ execute @e[type=armor_stand,name=col4,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col14,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~16 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=0,score_CPU_values=0] ~ ~ ~ execute @e[type=armor_stand,name=col5,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col14,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~8 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=0,score_CPU_values=0] ~ ~ ~ execute @e[type=armor_stand,name=col6,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col14,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~4 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=0,score_CPU_values=0] ~ ~ ~ execute @e[type=armor_stand,name=col7,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col14,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~2 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=0,score_CPU_values=0] ~ ~ ~ execute @e[type=armor_stand,name=col8,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col14,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~1 ~ ~
# Jump if positive
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col2,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col15,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~64 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col3,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col15,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~32 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col4,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col15,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~16 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col5,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col15,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~8 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col6,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col15,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~4 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col7,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col15,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~2 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col8,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col15,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~1 ~ ~
# Jump if negative
execute @e[type=armor_stand,name=pointer,score_CPU_values=-1] ~ ~ ~ execute @e[type=armor_stand,name=col2,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col16,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~64 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values=-1] ~ ~ ~ execute @e[type=armor_stand,name=col3,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col16,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~32 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values=-1] ~ ~ ~ execute @e[type=armor_stand,name=col4,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col16,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~16 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values=-1] ~ ~ ~ execute @e[type=armor_stand,name=col5,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col16,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~8 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values=-1] ~ ~ ~ execute @e[type=armor_stand,name=col6,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col16,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~4 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values=-1] ~ ~ ~ execute @e[type=armor_stand,name=col7,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col16,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~2 ~ ~
execute @e[type=armor_stand,name=pointer,score_CPU_values=-1] ~ ~ ~ execute @e[type=armor_stand,name=col8,score_CPU_instructions_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col16,score_CPU_instructions_min=1] ~ ~ ~ tp @e[type=armor_stand,name=pointer] ~1 ~ ~
# Tell not to go forward
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=0,score_CPU_values=0] ~ ~ ~ execute @e[type=armor_stand,name=col14,score_CPU_instructions_min=1] ~ ~ ~ scoreboard players set @e[type=armor_stand,name=jmp] CPU_values 1
execute @e[type=armor_stand,name=pointer,score_CPU_values_min=1] ~ ~ ~ execute @e[type=armor_stand,name=col15,score_CPU_instructions_min=1] ~ ~ ~ scoreboard players set @e[type=armor_stand,name=jmp] CPU_values 1
execute @e[type=armor_stand,name=pointer,score_CPU_values=-1] ~ ~ ~ execute @e[type=armor_stand,name=col16,score_CPU_instructions_min=1] ~ ~ ~ scoreboard players set @e[type=armor_stand,name=jmp] CPU_values 1