# Check which positions has the gold block
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~1 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col1] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~2 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col2] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~3 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col3] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~4 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col4] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~5 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col5] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~6 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col6] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~7 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col7] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~8 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col8] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~9 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col9] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~10 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col10] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~11 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col11] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~12 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col12] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~13 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col13] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~14 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col14] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~15 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col15] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~16 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col16] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~17 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col17] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~18 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col18] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~19 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col19] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~20 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col20] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~21 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col21] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~22 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col22] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~23 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col23] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~24 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col24] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~25 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col25] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~26 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col26] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~27 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col27] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~28 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col28] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~29 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col29] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~30 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col30] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~31 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col31] CPU_instructions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~32 minecraft:gold_block 0 scoreboard players set @e[type=armor_stand,name=col32] CPU_instructions 1
# Check which positions has the diamond block
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~1 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col1] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~2 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col2] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~3 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col3] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~4 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col4] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~5 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col5] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~6 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col6] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~7 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col7] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~8 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col8] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~9 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col9] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~10 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col10] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~11 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col11] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~12 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col12] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~13 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col13] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~14 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col14] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~15 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col15] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~16 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col16] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~17 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col17] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~18 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col18] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~19 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col19] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~20 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col20] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~21 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col21] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~22 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col22] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~23 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col23] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~24 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col24] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~25 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col25] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~26 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col26] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~27 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col27] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~28 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col28] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~29 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col29] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~30 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col30] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~31 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col31] CPU_initialise 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~32 minecraft:diamond_block 0 scoreboard players set @e[type=armor_stand,name=col32] CPU_initialise 1
# Check which positions has the iron block
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~1 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col1] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~2 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col2] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~3 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col3] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~4 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col4] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~5 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col5] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~6 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col6] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~7 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col7] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~8 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col8] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~9 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col9] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~10 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col10] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~11 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col11] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~12 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col12] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~13 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col13] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~14 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col14] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~15 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col15] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~16 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col16] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~17 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col17] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~18 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col18] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~19 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col19] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~20 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col20] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~21 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col21] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~22 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col22] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~23 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col23] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~24 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col24] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~25 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col25] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~26 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col26] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~27 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col27] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~28 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col28] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~29 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col29] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~30 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col30] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~31 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col31] CPU_functions 1
execute @e[type=armor_stand,name=pointer] ~ ~ ~ detect ~ ~ ~32 minecraft:iron_block 0 scoreboard players set @e[type=armor_stand,name=col32] CPU_functions 1